program: transmil/main_trans.py
project: TRANSMIL_first
name: tuning_threshold
description: tuning decision threshold
method: grid
metric:
 name: f1_score
 goal: maximize

parameters: 
 fold:
  values: [0, 1, 2, 3, 4]
  
 l_rate: 
  value: 1e-4
  #values: [5e-5, 1e-5] 
 decision_thr:
 # value: 0.5
  values: [0.2, 0.26, 0.3, 0.36, 0.4, 0.5, 0.6, 0.7, 0.8]
 batch_size: 
  value: 64
  #values: [32, 64]

 numb_frames: 
  value: 16
  #values: [8, 16, 32, 64, 128]

 epochs: 
  value: 100

 att_dim: 
  value: 256
  #values: [64, 128]

 n_layers: 
  value: 2
  #values: [2, 3]

 n_heads: 
  value: 8
  #values: [4, 8]

 dropout:         #oss: dropout viene usato solo se use_mlp=True!!! 
  value: 0
  #values: [0.1, 0.3]

 use_mlp: 
  value: False
  #values: [False, True]