program: transmil/main_trans.py
project: TRANSMIL_first
method: grid
metric:
 name: f1_score
 goal: maximize

#run lr=0.00001 per different attention dimensions a più epoche
#try once use_mlp=True with dropout \in {0.1, 0.3, 0.5}
#last sweep on number of frames
parameters: 
 fold:
  values: [0, 1, 2, 3, 4]
  
 l_rate: 
  value: 5e-5
  #values: [5e-5, 1e-5] 

 batch_size: 
  value: 32
  #values: [32, 64]

 numb_frames: 
  value: 16
  #values: [8, 16, 32, 64, 128]

 epochs: 
  value: 500

 att_dim: 
  value: 64
  #values: [64, 128]

 n_layers: 
  value: 2
  #values: [2, 3]

 n_heads: 
  value: 2
  #values: [4, 8]

 dropout:         #oss: dropout viene usato solo se use_mlp=True!!! 
  value: 0.5
  #values: [0.1, 0.3]

 use_mlp: 
  value: True
  #values: [False, True]