program: transmil/main_trans.py
project: TRANSMIL_first
method: grid
metric:
 name: f1_score
 goal: maximize

parameters: 
 fold:
  values: [0, 1, 2, 3, 4]
  
 l_rate: 
  value: 1e-4
  #values: [1e-3, 1e-4, 5e-5, 1e-5] 

 batch_size: 
  value: 64
  #values: [32, 64]

 numb_frames: 
  value: 16
  #values: [8, 16, 32, 64, 128]

 epochs: 
  value: 100

 att_dim: 
  #value: 256
  values: [128, 256, 512]

 n_layers: 
  #value: 2
  values: [2, 3]

 n_heads: 
  #value: 4
  values: [4, 8]

 dropout: 
  #value: 0
  values: [0.0, 0.1, 0.3]

 use_mlp: 
  value: False
  #values: [False, True]