program: main.py
project: GNN_sweep
name: simple_small_hd
description: simple model, with smaller hidden dimension = 128
method: grid
metric:
 name: f1_score
 goal: maximize

parameters: 
 fold:
  values: [0, 1, 2, 3, 4]
  
 numb_frames:
  value: 16
  #values: [32, 64, 128]
  
 l_rate:
  value: 1e-4

 batch_size: 
  value: 64
  #values: [32, 64]

 epochs: 
  value: 100

 k: 
  value: 3
  #values: [3, 8, 15]
 
 hidden_dim:
  value: 128
  #values: [128, 256, 512]

 pooling:
  value: 'mean'
  #values: ['mean', 'max', 'attention']

 layers:
  value: 2
  #values: [1, 2, 3]

 #topk_ratio:
 # values: [0.2, 0.3]