program: main.py
project: GNN_sweep
name: clusters_model_newcode
description: sweep with clusters model (both 1 and 2) and adapted unique code for three types of model
method: grid
metric:
 name: f1_score
 goal: maximize

parameters: 
 fold:
  values: [0, 1, 2, 3, 4]
  
 numb_frames:
  value: 16
  #values: [32, 64, 128]
  
 l_rate:
  value: 5e-5
  #values: [1e-4, 5e-5]

 batch_size: 
  value: 64
  #values: [32, 64]

 epochs: 
  value: 150

 k: 
  #value: 3
  values: [3, 8, 15]
 
 hidden_dim:
  #value: 128
  values: [128, 256, 512]

 pooling:
  value: 'mean'
  #values: ['mean', 'max', 'attention']

 layers:
  values: [1, 2]

 #topk_ratio:
 # values: [0.2, 0.3, 0.4]

 num_clusters:
  values: [1, 2]